name: wifi_guardian
description: WiFi Security Scanner
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.3
  fluttertoast: ^8.2.2
  network_info_plus: ^4.0.0

flutter:
  uses-material-design: true
